[mypy]
python_version = 3.10
mypy_path = backend
files = backend/configuration_model.py, backend/system_configuration.py, backend/build_app_config.py, backend/user_config_api.py
follow_imports = silent
disallow_untyped_defs = True
check_untyped_defs = True
warn_unused_ignores = True
show_error_codes = True
