#!/usr/bin/env python3
"""Compile the deployable AppDaemon config from system and user sources."""

from __future__ import annotations

import argparse
import copy
from pathlib import Path
from typing import Any

import yaml

BACKEND_DIR = Path(__file__).resolve().parent
CONFIG_DIR = BACKEND_DIR / "config"
SYSTEM_CONFIG_PATH = CONFIG_DIR / "system_config.yml"
USER_CONFIG_PATH = CONFIG_DIR / "user_config.yml"
OUTPUT_PATH = BACKEND_DIR / "app_cfg.yaml"


def deep_merge(base: dict[str, Any], override: dict[str, Any]) -> dict[str, Any]:
    """Recursively merge mappings while replacing scalar and list values."""

    merged = copy.deepcopy(base)
    for key, value in override.items():
        if isinstance(value, dict) and isinstance(merged.get(key), dict):
            merged[key] = deep_merge(merged[key], value)
        else:
            merged[key] = copy.deepcopy(value)
    return merged


def load_mapping(path: Path) -> dict[str, Any]:
    """Load one YAML source and require a mapping root."""

    value = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain a YAML mapping")
    return value


def compile_config(
    system_path: Path = SYSTEM_CONFIG_PATH,
    user_path: Path = USER_CONFIG_PATH,
) -> dict[str, Any]:
    """Return the complete AppDaemon configuration."""

    system = load_mapping(system_path)
    user = load_mapping(user_path)
    app_definition = system.get("app_definition")
    app_config = system.get("app_config")
    runtime_defaults = system.get("runtime_defaults")
    user_config = user.get("user_config")
    for name, value in (
        ("app_definition", app_definition),
        ("app_config", app_config),
        ("runtime_defaults", runtime_defaults),
        ("user_config", user_config),
    ):
        if not isinstance(value, dict):
            raise ValueError(f"Missing mapping: {name}")
    merged_user_config = deep_merge(runtime_defaults, user_config)
    system_components = runtime_defaults.get("safety_components", {})
    user_components = user_config.get("safety_components", {})
    merged_components = merged_user_config.get("safety_components", {})
    collection_names = {
        "ExternalHazardComponent": "openings",
        "SafetyDoorsComponent": "doors",
        "TemperatureComponent": "rooms",
    }
    for component_name, collection_name in collection_names.items():
        user_component = user_components.get(component_name)
        if not isinstance(user_component, dict):
            continue
        user_collection = user_component.get(collection_name)
        if not isinstance(user_collection, dict):
            continue
        system_collection = system_components.get(component_name, {}).get(
            collection_name, {}
        )
        merged_components[component_name][collection_name] = {
            key: deep_merge(
                system_collection.get(key, {}),
                value,
            )
            for key, value in user_collection.items()
        }

    return {
        "SafetyFunctions": {
            **copy.deepcopy(app_definition),
            "app_config": copy.deepcopy(app_config),
            "user_config": merged_user_config,
        }
    }


def write_compiled_config(config: dict[str, Any], output_path: Path) -> None:
    """Write deterministic generated YAML with an ownership header."""

    body = yaml.safe_dump(
        config,
        allow_unicode=True,
        default_flow_style=False,
        sort_keys=False,
    )
    output_path.write_text(
        "# Generated by backend/build_app_config.py.\n"
        "# Edit backend/config/user_config.yml for installation bindings or\n"
        "# backend/config/system_config.yml for software policy/calibration.\n"
        + body,
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    compiled = compile_config()
    if args.check:
        existing = load_mapping(OUTPUT_PATH)
        if existing != compiled:
            raise SystemExit("backend/app_cfg.yaml is not up to date")
        return
    write_compiled_config(compiled, OUTPUT_PATH)


if __name__ == "__main__":
    main()
