#!/usr/bin/env python3
"""Compile the deployable AppDaemon config from system and user sources."""

from __future__ import annotations

import argparse
import copy
import json
from pathlib import Path
from typing import Any

import yaml

from configuration_model import (
    CONFIGURATION_MODEL_VERSION,
    compile_user_config_v2,
    user_configuration_schema,
)

BACKEND_DIR = Path(__file__).resolve().parent
CONFIG_DIR = BACKEND_DIR / "config"
SYSTEM_CONFIG_PATH = CONFIG_DIR / "system_config.yml"
USER_CONFIG_PATH = CONFIG_DIR / "user_config.yml"
OUTPUT_PATH = BACKEND_DIR / "app_cfg.yaml"


def load_mapping(path: Path) -> dict[str, Any]:
    """Load one YAML source and require a mapping root."""

    value = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain a YAML mapping")
    return value


def compile_config(
    system_path: Path = SYSTEM_CONFIG_PATH,
    user_path: Path = USER_CONFIG_PATH,
) -> dict[str, Any]:
    """Return the complete AppDaemon configuration."""

    system = load_mapping(system_path)
    user = load_mapping(user_path)
    app_definition = system.get("app_definition")
    app_config = system.get("app_config")
    runtime_defaults = system.get("runtime_defaults")
    user_config = user.get("user_config")
    for name, value in (
        ("app_definition", app_definition),
        ("app_config", app_config),
        ("runtime_defaults", runtime_defaults),
        ("user_config", user_config),
    ):
        if not isinstance(value, dict):
            raise ValueError(f"Missing mapping: {name}")

    model_version = user_config.get("model_version")
    if model_version != CONFIGURATION_MODEL_VERSION:
        raise ValueError(
            f"Unsupported user_config.model_version={model_version}; "
            f"supported={CONFIGURATION_MODEL_VERSION}"
        )
    configured_version = system.get("configuration_model", {}).get("version")
    if configured_version != CONFIGURATION_MODEL_VERSION:
        raise ValueError(
            "system configuration_model.version does not support "
            f"user model_version={model_version}"
        )
    merged_user_config = compile_user_config_v2(runtime_defaults, user_config)

    return {
        "SafetyFunctions": {
            **copy.deepcopy(app_definition),
            "app_config": copy.deepcopy(app_config),
            "user_config": merged_user_config,
        }
    }


def write_compiled_config(config: dict[str, Any], output_path: Path) -> None:
    """Write deterministic generated YAML with an ownership header."""

    body = yaml.safe_dump(
        config,
        allow_unicode=True,
        default_flow_style=False,
        sort_keys=False,
    )
    output_path.write_text(
        "# Generated by backend/build_app_config.py.\n"
        "# Edit backend/config/user_config.yml for the installation model or\n"
        "# backend/config/system_config.yml for software policy/calibration.\n" + body,
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument(
        "--print-user-schema",
        action="store_true",
        help="Print the complete user_config model v2 JSON Schema and exit.",
    )
    parser.add_argument(
        "--system",
        type=Path,
        default=SYSTEM_CONFIG_PATH,
        help="Path to the system policy and calibration source.",
    )
    parser.add_argument(
        "--user",
        type=Path,
        default=USER_CONFIG_PATH,
        help="Path to the installation-owned configuration source.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=OUTPUT_PATH,
        help="Path for the generated AppDaemon apps file.",
    )
    args = parser.parse_args()
    if args.print_user_schema:
        print(
            json.dumps(
                user_configuration_schema(),
                ensure_ascii=False,
                indent=2,
            )
        )
        return
    compiled = compile_config(system_path=args.system, user_path=args.user)
    if args.check:
        existing = load_mapping(args.output)
        if existing != compiled:
            raise SystemExit(f"{args.output} is not up to date")
        return
    write_compiled_config(compiled, args.output)


if __name__ == "__main__":
    main()
